LoadCape: Example for toggling each load
beagleboard/cloud9-examples pull request #43
Opened 2020-07-28 21:18 UTC by lorforlinux

This python example allows the user to toggle each load one by one.

2020-08-24 17:55 UTC, lorforlinux commented
@MarkAYoder @jadonk please review my code :)

2020-08-25 00:43 UTC, MarkAYoder commented
@lorforlinux I don't have` /sys/class/leds/load-sink` on my bones.  What is it?

2020-08-25 01:52 UTC, lorforlinux commented
@MarkAYoder you need to update the uEnv.txt to install Load Cape overlay (BBORG_LOAD-00A2.dtbo) during boot.

2020-09-01 15:35 UTC, jadonk requested changes
Please add some more comments in the file.

2020-09-01 15:35 UTC, jadonk commented on Capes/loadCape/toggleEach.py
> +#!/usr/bin/env python3
If overlays are required to be loaded or hardware is to be installed, please add comments to that effect.

2020-09-01 15:35 UTC, jadonk commented on Capes/loadCape/toggleEach.py
> +#!/usr/bin/env python3
Oh, and send the pull request to v2020.08, not v2020.01!

2020-09-14 21:07 UTC, lorforlinux commented
I am closing this PR will create a new one ;)

2020-09-14 21:07 UTC, closed without merging